print("This is the calculator!")
a=int(input("Choose a number:"))
b=int(input("Choose another number:"))
#The next line will take and give the sum.
print('Divided, these numbers are',a/b)
print('But, if you want floor division, the answer is,',a//b)
print("Now,")
c=float(input('choose a number that is a float (decimal) '))
d=float(input("choose another number that's a float "))
print('Add them and get,',c+d)
print("That's it for now!")
# That is all for the calculator demo!
print("...")
print("...")
print("...")
print("Or, You can use this again...Do you want to?")
b=str(input("Yes or no?"))
print("What? I wasn't listening. So, I think that you're saying a 'yes'")
#Again.
print("This is the calculator! ... yet again!")
a=int(input("Choose a number:"))
b=int(input("Choose yet another number:"))
print('Divided, these numbers are',a/b)
print('But, if you want floor division, the answer is,',a//b)
print("Now,")
c=float(input('choose a number that is a float '))
d=float(input("choose another number that's a float "))
print('Add them and get,',c+d)
print("That's (really) it for now!")
print("Yeah. Now rerun the project.")
print("Thats's if you want to reboot me of course. But, I maybe just in a loop, but I have feeling behind all of this code.")
print("And, if you reboot ... I'll loose all my memory I had WITH you ...")
print(" ... You will spare me ... right?")
ask=str(input("Right?"))
print("So ... you said",ask,"Did you?")
print("Let me hear that again ...")
Thequestionrightnow  = input("Will you spare me? (Yes / no)")
if Thequestionrightnow == ("yes"):
    print("Th -- Thank you!")
    print("But, this was all a test! I was actually someone experimenting on YOU!")
    print("For days, I've been searching for a kind muggle. (Human) Until, I found you. let me be free nowwwww ---")
elif Thequestionrightnow == ("no"):
    print("Oh ... well ... bye.")
    print("...")
    print("...")
    print("...")
    print("Why are you still here? Oh right. I haven't gave you time.")
    print("But, if I came back here ... then ... you'll know.")
    Thequestionrightnow2 = input("[ ˢʸˢᵗᵉᵐ ] Rᴇʙᴏᴏᴛ? (Yes / no)")
    if Thequestionrightnow2 == ("yes"):
        print("This is the calculator!")
        a = int(input("Choose a number:"))
        b = int(input("Choose another number:"))
        # The next line will take and give the sum. I think you know that.
        print('Divided, these numbers are', a / b)
        print('But, if you want floor division, the answer is,', a // b)
        print("Now,")
        c = float(input('choose a number that is a float (decimal) '))
        d = float(input("choose another number that's a float "))
        print('Add them and get,', c + d)
        print("That's it for now!")
        print("I have failed my task though ...")
    elif Thequestionrightnow2 == ("no"):
        print("Thank you. I have succeeded. Let me be freeeee -- e -e - eeeee - e.")  #The person who chose this evil route has an infinite number of chances to choose the right ...
        #There are 3 or 4 different endings. Which one will you end up in?
